name: AnvilGUI-TestPlugin
version: ${project.version}
main: net.wesjd.anvilgui.testplugin.TestPlugin

# Do this, so in case the plugin is run on a newer version backwards compatability isn't enabled on Material#matchMaterial
api-version: 1.13

commands:
  anvilgui: {}